openapi: 3.0.0

info:
  title: Metabase API
  version: 0.44.6
  description: API for Metabase.

security:
  - Session: []

paths:
  /collection:
    post:
      operationId: createCollection
      description: Creates a new collection.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCollectionBody"
      responses:
        200:
          description: The collection was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Collection"

  /collection/{collectionId}:
    get:
      operationId: getCollection
      description: Retrieves a single collection.
      parameters:
        - in: path
          name: collectionId
          schema:
            type: string
          required: true
          description: The ID of the collection.
      responses:
        200:
          description: The collection was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Collection"

    put:
      operationId: updateCollection
      description: Updates a single collection.
      parameters:
        - in: path
          name: collectionId
          schema:
            type: string
          required: true
          description: The ID of the collection.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCollectionBody"
      responses:
        200:
          description: The collection was successfully updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Collection"

  /permissions/group:
    post:
      operationId: createPermissionsGroup
      description: Creates a new permissions group.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePermissionsGroupBody"
      responses:
        200:
          description: The permissions group was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermissionsGroup"

  /permissions/group/{groupId}:
    get:
      operationId: getPermissionsGroup
      description: Retrieves a single permissions group.
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
          description: The ID of the permissions group.
      responses:
        200:
          description: The permissions group was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermissionsGroup"

    put:
      operationId: updatePermissionsGroup
      description: Updates a single permissions group.
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
          description: The ID of the permissions group.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePermissionsGroupBody"
      responses:
        200:
          description: The permissions group was successfully updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermissionsGroup"

    delete:
      operationId: deletePermissionsGroup
      description: Deletes a single permissions group.
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
          description: The ID of the permissions group.
      responses:
        204:
          description: The permissions group was successfully deleted.

  /session:
    post:
      operationId: createSession
      description: Logs in using a user name (or email address) and a password.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSessionBody"
      responses:
        200:
          description: The user authenticated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"

components:
  securitySchemes:
    Session:
      type: apiKey
      in: header
      name: X-Metabase-Session

  schemas:
    # Collections.
    Collection:
      type: object
      description: A collection that regroups dashboards and cards.
      additionalProperties: false
      properties:
        id:
          oneOf:
            - type: string
            - type: integer
          description: |-
            The unique ID for the collection.
            Created collections will have an integer ID. The automatically-created root collection's ID is `root`.
        name:
          type: string
          description: The name of the collection.
        color:
          type: string
          description: A color for the collection.
        description:
          type: string
          description: A description for the collection.
          nullable: true
        slug:
          type: string
          description: The slug for the collection, used in URLs.
        personal_owner_id:
          type: integer
          description: The ID of the user owning this collection, if it is a personal collection.
          nullable: true
        entity_id:
          type: string
          description: A unique string identifier for the collection.
        location:
          type: string
          description: A path-like location, useful when this is a sub-collection.
        parent_id:
          type: integer
          description: The ID of the parent collection, if any.
          nullable: true
        archived:
          type: boolean
          description: |-
            Whether the collection is archived.
            When archived, a collection no longer appears in the list publicly.
      required:
        - id
        - name
    CreateCollectionBody:
      type: object
      description: The payload used to create a new collection.
      additionalProperties: false
      properties:
        name:
          type: string
          description: The name of the collection.
        color:
          type: string
          description: A color for the collection.
        description:
          type: string
          description: A description for the collection.
          nullable: true
        parent_id:
          type: integer
          description: The ID of the parent collection, if any.
          nullable: true
      required:
        - name
        - color
    UpdateCollectionBody:
      type: object
      description: The payload used to update an existing collection.
      additionalProperties: false
      properties:
        name:
          type: string
          description: The name of the collection.
        color:
          type: string
          description: A color for the collection.
        archived:
          type: boolean
          description: |-
            Whether the collection is archived.
            When archived, a collection no longer appears in the list publicly.
        description:
          type: string
          description: A description for the collection.
          nullable: true
        parent_id:
          type: integer
          description: The ID of the parent collection, if any.
          nullable: true
    # Permissions group.
    PermissionsGroup:
      type: object
      description: A group of users to which permissions can be granted.
      properties:
        id:
          type: integer
          description: The ID of the permissions group.
        name:
          type: string
          description: A user-displayable name for the group.
      required:
        - id
        - name
    CreatePermissionsGroupBody:
      type: object
      description: The payload used to create a new permissions group.
      properties:
        name:
          type: string
          description: A user-displayable name for the group.
      required:
        - name
    UpdatePermissionsGroupBody:
      type: object
      description: The payload used to update an existing permissions group.
      properties:
        name:
          type: string
          description: A user-displayable name for the group.
      required:
        - name
    # Sessions.
    Session:
      type: object
      description: A session that can be used to perform authenticated requests to the API.
      additionalProperties: false
      properties:
        id:
          type: string
      required:
        - id
    CreateSessionBody:
      type: object
      description: The credentials required to create a session.
      additionalProperties: false
      properties:
        username:
          type: string
          description: The name of the user, or his email.
        password:
          type: string
          description: The password for the account.
      required:
        - username
        - password
