name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build provider
        run: make provider

      - name: Build mbtf
        run: make mbtf

      - name: Run tests
        run: make testacc-with-setup
